### PR TITLE
Audio alert 🎺

### PR DESCRIPTION
**Pull request by pellebjerkestrand**
Adds audio alert on new notification. Currently supports frequencies.

`Yas` on build will have to wait until v2 😞.

Browsers block playback unless a user has indicated that audio playback is OK, so the unmute button has to be there.

### CODE REVIEW

**Comment by pellebjerkestrand** [comment]
I'm not really happy with the look of the buttons, but I'm no designer 🤷🏻‍♂️.

**Comment by asbjornh** [comment]
> I'm not really happy with the look of the buttons, but I'm no designer 🤷🏻‍♂️.

Double the border radius and double the horizontal padding and they look quite nice :)

**Comment by asbjornh** [comment]
Cool stuff!

**Comment by pellebjerkestrand** [comment]
The `createStereoPanner` is not available everywhere and crashes some browsers: `TypeError: context.createStereoPanner is not a function. (In 'context.createStereoPanner()', 'context.createStereoPanner' is undefined)`.

**Comment by asbjornh** [comment]
```
if(!context.createStereoPanner) {
  monoDelay(context, inputNode, time, gain, feedback, outputNode);
  return;
}
```

**Pull request merged**
